baseURL = "https://www.tommyc.net"
languageCode = "en-us"
defaultContentLanguage = "en"
publishDir = "/Users/tommy/Sites/-Prod/tommyc.net"
title = "Tommy Craft"
theme = "hermit"
enableGitInfo = false #Controls if the GitHub link for the commit appears on the post)
pygmentsCodefences  = true
pygmentsUseClasses  = true
# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "Tommy Craft"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  category = ""  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 3:04 MST"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "The permanent home of my temporary insanties."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/djfriar/tommyc.net/commit/"

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/djfriar"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/djfriar"

  [[params.social]]
    name = "github"
    url = "https://github.com/djfriar"

[menu]

  [[menu.main]]
    name = "Motorcycling"
    url = "motorcycle/"
    weight = 10

  [[menu.main]]
    name = "Dev"
    url = "projects/"
    weight = 20

  [[menu.main]]
    name = "Random"
    url = "posts/"
    weight = 30
