baseURL = "https://www.tommyc.net"
LanguageCode = "en-us"
defaultContentLanguage = "en"
publishDir = "/User/tommy/Sites/-Prod/tommyc.net"
title = "Tommy Craft"
theme = "Crafted"

[author]
  name = "Tommy Craft"

[params]
  #Date Formatting
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 3:04 MST"

  homeSubtitle = "The permanent home of my temporary insanities."

  [[params.motorcycling]]
      detail = "What I Ride"
      url = "motorcycle/bike"

  [[params.development]]
      detail = "How I Code"
      url = "projects/Coding-Gear"

  #Social Icons
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/djfriar"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/djfriar"

  [[params.social]]
    name = "github"
    url = "https://github.com/djfriar"

[menu]

  [[menu.main]]
    name = "Motorcycling"
    url = "motorcycle/"
    weight = 10

  [[menu.main]]
    name = "Development"
    url = "projects/"
    weight = 20

  [[menu.main]]
    name = "Photography"
    url = "photos/"
    weight = 30

  [[menu.main]]
    name = "Potpourri"
    url = "posts/"
    subName = "What I Shoot"
    subURL = "photos/Camera-Gear"
    weight = 40